=== OpenExynos/android_vendor_samsung_slsi_mx140_firmware/mx140/mx140_t/debug/hardware/moredump/Memory.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Define an address range -->
  <xs:complexType name="addressRange">
    <xs:attribute name="startAddr" type="xs:hexBinary" use="required" />
    <xs:attribute name="endAddr" type="xs:hexBinary" use="required" />
  </xs:complexType>

  <!-- Define a region -->
  <xs:complexType name="region">
    <xs:complexContent>
      <xs:extension base="addressRange">
        <xs:attribute name="name" type="xs:string" use="optional" />
        <xs:attribute name="comment" type="xs:string" use="optional" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="memory">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded">
          <!-- Define the mmap range -->
          <!-- Memory regions outwith R4/M4 that fall within the mmap range will use the mmap interface (android only) -->
          <xs:element name="mmap" minOccurs="1" maxOccurs="1" type ="addressRange" />

          <!-- Memory that will be read over any available interface, mmap, r4 or m4 (in that order) -->
          <!-- This element can occur before R4 and/or between R4/M4 and/or after M4-->
          <xs:element minOccurs="0" maxOccurs="unbounded" name="region" type="region" />

          <!-- Memory specific to (and will only be read via) R4 -->
          <!-- will also be wrapped with IF (CPUIS("CortexR4")) in CMM -->
          <xs:element name="R4" minOccurs="0" maxOccurs="1">
            <xs:complexType>
              <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" name="region" type="region" />
              </xs:sequence>
            </xs:complexType>
          </xs:element>

          <!-- Memory specific to (and will only be read via) M4 -->
          <!-- will also be wrapped with IF (CPUIS("CortexM4")) in CMM -->
          <xs:element name="M4" minOccurs="0" maxOccurs="1">
            <xs:complexType>
              <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" name="region" type="region" />
              </xs:sequence>
            </xs:complexType>
          </xs:element>

        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== OpenExynos/android_vendor_samsung_slsi_mx140_firmware/mx140/mx140/debug/hardware/moredump/moredump_memory.xml
<?xml version="1.0" encoding="utf-8"?>

<!--
(c) SCSC 2015 Maxwell moredump memory definitions
    From http://wiki/Maxwell140MemoryMap
-->

<memory xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.samsung.com Memory.xsd">
  <!-- Define the mmap range - DO NOT CHANGE THIS -->
  <mmap startAddr="80000000" endAddr="803FFFFF"/>
  <R4>
    <!-- Memory specific to (and will only be read via) R4 -->
    <region startAddr="00000000" endAddr="00007fff" name="TCMA" comment=""/>
    <region startAddr="00018000" endAddr="0001ffff" name="TCMB1" comment=""/>
  </R4>
  <M4>
    <!--  Memory specific to (and will only be read via) M4 -->
  </M4>
  <!--  Memory that can be read via R4 or M4 (or possibly mmap) -->
  <region startAddr="07FE0000" endAddr="07FFFFFF" name="RAMCB" comment="128KB" />
  <region startAddr="08000000" endAddr="08013FFF" name="RAMSB" comment="80KB" />
  <region startAddr="80000000" endAddr="803FFFFF" name="DRAM" comment="4MB" />
  <region startAddr="C0000000" endAddr="C0017FFF" name="RAMSW ASIC" comment="96KB" />
  
  <region startAddr="A0580000" endAddr="A0580003" name="MAILBOX_AP_APM 1" comment="MCU Controller" />
  <region startAddr="A0580008" endAddr="A058002F" name="MAILBOX_AP_APM 2" comment="Interrupt registers" /> 
  <region startAddr="A058004C" endAddr="A0580053" name="MAILBOX_AP_APM 3" comment="INIT/VERSION" /> 
  <region startAddr="A0580080" endAddr="A058009F" name="MAILBOX_AP_APM 4" comment="Shared registers" /> 
</memory>
