=== OpenExynos/android_vendor_samsung_slsi_mx140_firmware/mx140/mx140_t/debug/hardware/moredump/Registers.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Define the permissible memory classes -->
  <xs:simpleType name="class">
    <xs:restriction base="xs:string">
      <!-- Data memory -->
      <xs:enumeration value="D" />
      <!-- Data memory (supervisor access) -->
      <xs:enumeration value="S" />
      <!-- CP14 -->
      <xs:enumeration value="C14" />
      <!-- CP15 -->
      <xs:enumeration value="C15" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Define the permissible set of register widths in octets -->
  <xs:simpleType name="width">
    <xs:restriction base="xs:unsignedByte">
      <xs:enumeration value="1" />
      <xs:enumeration value="2" />
      <xs:enumeration value="4" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Define the read/write capability flags -->
  <xs:simpleType name="rw_flags">
    <xs:restriction base="xs:string">
      <xs:enumeration value="R" />
      <xs:enumeration value="W" />
      <xs:enumeration value="RW" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Define a basic register -->
  <xs:complexType name="register">
    <xs:attribute name="addr" type="xs:hexBinary" use="required" />
    <xs:attribute name="width" type="width" use="required" />
    <xs:attribute name="rw_flags" type="rw_flags" use="required" />
    <xs:attribute name="name" type="xs:string" use="optional" />
    <xs:attribute name="comment" type="xs:string" use="optional" />
  </xs:complexType>

  <!-- Define a bit-field within a register -->
  <xs:complexType name="registerfield">
    <xs:complexContent>
      <xs:extension base="register">
        <xs:attribute name="shift" type="xs:unsignedShort" use="required" />
        <xs:attribute name="mask" type="xs:string" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <!-- Define an index register -->
  <xs:complexType name="indexregister">
    <xs:complexContent>
      <xs:extension base="register">
        <xs:choice minOccurs="1" maxOccurs="1">
          <!-- Either an absolute count -->
          <xs:element name="count">
            <xs:complexType>
              <xs:attribute name="value" type="xs:unsignedShort" use="required" />
            </xs:complexType>
          </xs:element>
          <!-- or obtained indirectly from a register field -->
          <xs:element name="countfrom" type="registerfield" />
        </xs:choice>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <!-- Define a table -->
  <xs:complexType name="table">
    <xs:sequence>
      <!-- The one and only index register -->
      <xs:element name="indexregister" type="indexregister" minOccurs="1" maxOccurs="1" />
      <!-- and at least 1 other register in the table -->
      <xs:element name="register" type="register" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required" />
  </xs:complexType>


  <!-- Define a block -->
  <xs:complexType name="block">
    <!-- containing a number of tables or registers -->
    <xs:choice maxOccurs="unbounded">
      <xs:element name="register" type="register" />
      <xs:element name="table" type="table" />
    </xs:choice>
    <xs:attribute name="name" type="xs:string" use="optional" />
    <xs:attribute name="comment" type="xs:string" use="optional" />
    <xs:attribute name="description" type="xs:string" use="optional" />
  </xs:complexType>

  <!-- Define a memory-mapped region -->
  <xs:complexType name="memory">
    <xs:choice maxOccurs="unbounded">
      <xs:element minOccurs="1" maxOccurs="unbounded" name="register" type="register" />
      <xs:element name="block" type="block" />
      <xs:element name="table" type="table" />
    </xs:choice>
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="class" type="class" use="required"/>
  </xs:complexType>

  <!-- Define a Cortex R4 co-processor -->
  <xs:complexType name="coprocessor">
    <xs:sequence>
      <xs:element name="block" minOccurs="1" maxOccurs="unbounded">
        <xs:complexType>
          <xs:choice maxOccurs="unbounded">
            <xs:element name="register" type="register" />
            <xs:element name="table" type="table" />
          </xs:choice>
          <xs:attribute name="name" type="xs:string" use="required" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="id" type="class" use="required" />
  </xs:complexType>

  <!-- Define a subsystem, top-level element for 'digits' registers -->
  <xs:element name="subsystem">
    <xs:complexType>
      <xs:sequence>
        <!-- containing a number of blocks -->
        <xs:element minOccurs="1" maxOccurs="unbounded" name="block" type="block" />
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <!-- Define a Cortex processor -->
  <xs:element name="processor">
    <xs:complexType>
      <xs:choice minOccurs="1" maxOccurs="unbounded">
        <xs:element name="coprocessor" type="coprocessor" />
        <xs:element name="memory" type="memory" />
      </xs:choice>
      <xs:attribute name="name" type="xs:string" use="required" />
      <xs:attribute name="comment" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

</xs:schema>

=== OpenExynos/android_vendor_samsung_slsi_mx140_firmware/mx140/mx140/debug/hardware/moredump/cortexR4.xml
<?xml version="1.0" encoding="utf-8"?>

<!--
(c) SCSC 2015.

  XML file defining Cortex R4 moredump
-->

<processor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.samsung.com Registers.xsd"
  name="Cortex R4" comment="Cortex R4 On-Chip Peripherals">
  <coprocessor name="System Control" id="C15">
    <block name="ID Registers">
      <register addr="0000" rw_flags="RW" width="4" name="MIDR" comment="Main ID Register"/>
      <register addr="0100" rw_flags="RW" width="4" name="CTR" comment="Cache Type Register"/>
      <register addr="0200" rw_flags="RW" width="4" name="TCMTR" comment="Tightly-Coupled Memory Status Register"/>
      <register addr="0400" rw_flags="RW" width="4" name="MPUIR" comment="MPU type register"/>
      <register addr="0500" rw_flags="RW" width="4" name="MPIDR" comment="Multiprocessor Affinity Register"/>
      <register addr="0410" rw_flags="RW" width="4" name="MMFR0" comment="Memory Model Feature Register 0"/>
      <register addr="0510" rw_flags="RW" width="4" name="MMFR1" comment="Memory Model Feature Register 1"/>
      <register addr="0610" rw_flags="RW" width="4" name="MMFR2" comment="Memory Model Feature Register 2"/>
      <register addr="0710" rw_flags="RW" width="4" name="MMFR3" comment="Memory Model Feature Register 3"/>
      <register addr="0020" rw_flags="RW" width="4" name="ISAR0" comment="Instruction Set Attribute Register 0"/>
      <register addr="0120" rw_flags="RW" width="4" name="ISAR1" comment="Instruction Set Attribute Register 1"/>
      <register addr="0220" rw_flags="RW" width="4" name="ISAR2" comment="Instruction Set Attribute Register 2"/>
      <register addr="0320" rw_flags="RW" width="4" name="ISAR3" comment="Instruction Set Attribute Register 3"/>
      <register addr="0420" rw_flags="RW" width="4" name="ISAR4" comment="Instruction Set Attribute Register 4"/>
      <register addr="0520" rw_flags="RW" width="4" name="ISAR5" comment="Instruction Set Attribute Registers 5 (Reserved)"/>
      <register addr="0620" rw_flags="RW" width="4" name="ISAR6" comment="Instruction Set Attribute Registers 6 (Reserved)"/>
      <register addr="0720" rw_flags="RW" width="4" name="ISAR7" comment="Instruction Set Attribute Registers 7 (Reserved)"/>
      <register addr="0010" rw_flags="RW" width="4" name="PFR0" comment="Processor Feature Register 0"/>
      <register addr="0110" rw_flags="RW" width="4" name="PFR1" comment="Processor Feature Register 1"/>
      <register addr="0210" rw_flags="RW" width="4" name="DFR0" comment="Debug Feature Register 0"/>
      <register addr="0310" rw_flags="RW" width="4" name="AFR0" comment="Auxiliary Feature Register 0"/>
    </block>

    <block name="System Control and Configuration">
      <register addr="0001" rw_flags="RW" width="4" name="SCTLR" comment="Control Register"/>
      <register addr="0101" rw_flags="RW" width="4" name="ACTLR" comment="Auxiliary Control Register"/>
      <register addr="0201" rw_flags="RW" width="4" name="CPACR" comment="Coprocessor Access Control Register"/>
      <register addr="000b" rw_flags="RW" width="4" name="SPC" comment="Slave Port Control"/>
    </block>

    <block name="MPU Control and Configuration">
      <register addr="0005" rw_flags="RW" width="4" name="DFSR" comment="Data Fault Status Register"/>
      <register addr="0006" rw_flags="RW" width="4" name="DFAR" comment="Data Fault Address Register"/>
      <register addr="0105" rw_flags="RW" width="4" name="IFSR" comment="Instruction Fault Status Register"/>
      <register addr="0206" rw_flags="RW" width="4" name="IFAR" comment="Instruction Fault Address Register"/>
      <register addr="0015" rw_flags="RW" width="4" name="ADFSR" comment="Auxiliary Data Fault Status Register"/>
      <register addr="0115" rw_flags="RW" width="4" name="AIFSR" comment="Auxiliary Instruction Fault Status Register"/>
      <register addr="010d" rw_flags="RW" width="4" name="CONTEXTIDR" comment="Context ID Register"/>
      <table name="MPU Regions">
        <indexregister addr="0026" rw_flags="RW" width="4" name="MRNR" comment="Memory Region Number Register">
          <countfrom addr="0400" rw_flags="RW" width="4" name="MPUIR" comment="MPU type register" shift="8" mask="000F"/>
        </indexregister>
        <register addr="0016" rw_flags="RW" width="4" name="RBAR" comment="Region Base Address Register"/>
        <register addr="0216" rw_flags="RW" width="4" name="RSER" comment="Region Size and Enable Register"/>
        <register addr="0416" rw_flags="RW" width="4" name="RACR" comment="Region Access Control Register"/>
      </table>
    </block>

    <block name="Cache Control and Configuration">
      <register addr="1100" rw_flags="RW" width="4" name="CLIDR" comment="Cache Level ID Register"/>
      <register addr="1000" rw_flags="RW" width="4" name="CCSIDR" comment="Current Cache Size ID Register"/>
      <register addr="2000" rw_flags="RW" width="4" name="CSSELR" comment="Cache Size Selection Register"/>
      <register addr="003f" rw_flags="RW" width="4" name="CFLR" comment="Correctable Fault Location Register"/>
    </block>

    <block name="TCM Control and Configuration">
      <register addr="0019" rw_flags="RW" width="4" name="BTCM" comment="Data TCM Region Register"/>
      <register addr="0119" rw_flags="RW" width="4" name="ATCM" comment="Instruction TCM Region Register"/>
      <register addr="0029" rw_flags="RW" width="4" name="TCMSEL" comment="TCM Selection Register"/>
    </block>

    <block name="System Performance Monitor">
      <register addr="00C9" rw_flags="RW" width="4" name="PMNC" comment="Performance Monitor Control Register"/>
      <register addr="01C9" rw_flags="RW" width="4" name="CNTENS" comment="Count Enable Set Register"/>
      <register addr="02C9" rw_flags="RW" width="4" name="CNTENC" comment="Count Enable Clear Register"/>
      <register addr="03C9" rw_flags="RW" width="4" name="FLAG" comment="Overflow Flag Status Register"/>
      <register addr="00D9" rw_flags="RW" width="4" name="CCNT" comment="Cycle Count Register"/>
      <register addr="00E9" rw_flags="RW" width="4" name="USEREN" comment="User Enable Register"/>
      <register addr="01E9" rw_flags="RW" width="4" name="INTENS" comment="Interrupt Enable Set Register"/>
      <register addr="02E9" rw_flags="RW" width="4" name="INTENC" comment="Interrupt Enable Clear Register"/>
      <table name="Performance Counters">
        <indexregister addr="05C9" rw_flags="RW" width="4" name="PMNXSEL" comment="Performance Counter Selection Register">
          <count value="3"/>
        </indexregister>
        <register addr="01d9" rw_flags="RW" width="4" name="ESR" comment="Event Selection Register"/>
        <register addr="02d9" rw_flags="RW" width="4" name="PMCR" comment="Performance Monitor Count Register"/>
      </table>
    </block>
  </coprocessor>

  <coprocessor name="Debug Registers" id="C14">
    <block name="Processor Identifier Registers">
      <register addr="0340" rw_flags="RW" width="4" name="CPUID" comment="Main ID Register"/>
      <register addr="0341" rw_flags="RW" width="4" name="CACHETYPE" comment="Cache Type Register"/>
      <register addr="0343" rw_flags="RW" width="4" name="TLBTYPE" comment="TLB Type Register"/>
      <register addr="0348" rw_flags="RW" width="4" name="ID_PFR0" comment="Processor Feature Register 0"/>
      <register addr="0349" rw_flags="RW" width="4" name="ID_PFR1" comment="Processor Feature Register 1"/>
      <register addr="034a" rw_flags="RW" width="4" name="ID_DFR0" comment="Debug Feature Register 0"/>
      <register addr="034b" rw_flags="RW" width="4" name="ID_AFR0" comment="Auxiliary Feature Register 0"/>
      <register addr="034c" rw_flags="RW" width="4" name="ID_MMFR0" comment="Processor Feature Register 0"/>
      <register addr="034d" rw_flags="RW" width="4" name="ID_MMFR1" comment="Processor Feature Register 1"/>
      <register addr="034e" rw_flags="RW" width="4" name="ID_MMFR2" comment="Processor Feature Register 2"/>
      <register addr="034f" rw_flags="RW" width="4" name="ID_MMFR3" comment="Processor Feature Register 3"/>
      <register addr="0350" rw_flags="RW" width="4" name="ID_ISAR0" comment="ISA Feature Register 0"/>
      <register addr="0351" rw_flags="RW" width="4" name="ID_ISAR1" comment="ISA Feature Register 1"/>
      <register addr="0352" rw_flags="RW" width="4" name="ID_ISAR2" comment="ISA Feature Register 2"/>
      <register addr="0353" rw_flags="RW" width="4" name="ID_ISAR3" comment="ISA Feature Register 3"/>
      <register addr="0354" rw_flags="RW" width="4" name="ID_ISAR4" comment="ISA Feature Register 4"/>
      <register addr="0355" rw_flags="RW" width="4" name="ID_ISAR5" comment="ISA Feature Register 5"/>
    </block>

    <block name="Coresight Management Registers">
      <register addr="03bf" rw_flags="RW" width="4" name="DBGITMISCIN" comment="Integration Test Input Register"/>
      <register addr="03c0" rw_flags="RW" width="4" name="DBGITCTRL" comment="Integration Mode Control Register"/>
      <register addr="03e8" rw_flags="RW" width="4" name="DBGCLAIMSET" comment="Claim Tag Set Register"/>
      <register addr="03e9" rw_flags="RW" width="4" name="DBGCLAIMCLR" comment="Claim Tag Clear Register"/>
      <register addr="03ed" rw_flags="RW" width="4" name="DBGLSR" comment="Lock Status Register"/>
      <register addr="03ee" rw_flags="RW" width="4" name="DBGAUTHSTATUS" comment="Authentication Status Register"/>
      <register addr="03f2" rw_flags="RW" width="4" name="DBGDEVID" comment="Device Identifier (RESERVED)"/>
      <register addr="03f3" rw_flags="RW" width="4" name="DBGDEVTYPE" comment="Device Type"/>
      <register addr="03f8" rw_flags="RW" width="4" name="PID0" comment="Peripheral ID0"/>
      <register addr="03f9" rw_flags="RW" width="4" name="PID1" comment="Peripheral ID1"/>
      <register addr="03fa" rw_flags="RW" width="4" name="PID2" comment="Peripheral ID2"/>
